#!/usr/bin/env python3
"""Emit the Go source for the vendor's F-135 inversion table.

Mirrors ``tools/gen_kcms_clut_tables.py``: the table crosses into Go as
generated source rather than a runtime file read, so the Go engine has no
dependency on the Python tree at render time.

Source: ``tools/ansel/python-pipeline/vendor_invert_table.npy`` — the real
16,384-entry table captured from the F-135's own inversion (docs/74 §170).
The closed form ``clamp(14750 - 3500*log10(in), 0, 16383)`` is a ±1
approximation of it (87.5 % exact) and is the FALLBACK, never the source of
truth; see ``pakon_render._vendor_invert_lut``.

Usage:
    python3 tools/gen_vendor_invert_table.py            # write the .go file
    python3 tools/gen_vendor_invert_table.py --check    # verify it is current
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
NPY = ROOT / "tools" / "ansel" / "python-pipeline" / "vendor_invert_table.npy"
OUT = ROOT / "tools" / "ansel" / "pipeline" / "vendorinvert" / "tables.go"

HEADER = '''// Code generated by tools/gen_vendor_invert_table.py. DO NOT EDIT.
//
// Source: tools/ansel/python-pipeline/vendor_invert_table.npy
//         md5 {md5}
//
// The real 16,384-entry inversion table the F-135 applies BEFORE stage 2 —
// docs/74 §170-§175. Not a fit: this is the captured table itself. The closed
// form clamp(14750 - 3500*log10(in), 0, 16383) reproduces it exactly on
// 87.5 % of entries with a maximum error of 1, and is only ever a fallback.
//
// Using it in the vendor's position (before the polynomial, with no film
// base, no Dmin, no pedestal and no fpo) takes the six-frame comparison from
// 59.14 MAE / +58.90 bias to 23.59 / -3.18.

package vendorinvert

// NpyMD5 is the capture this table came from.
const NpyMD5 = "{md5}"

// Entries is the table length; the index is the raw 14-bit code, clamped.
const Entries = {n}

// Max is the largest value the table yields (14-bit ceiling).
const Max = {mx}

// Table is the vendor's inversion, indexed 0..Entries-1.
var Table = [Entries]uint16{{
'''


def build() -> tuple[str, str]:
    raw = NPY.read_bytes()
    md5 = hashlib.md5(raw).hexdigest()
    t = np.load(NPY)
    if t.ndim != 1:
        raise SystemExit(f"expected a 1-D table, got shape {t.shape}")
    if t.min() < 0 or t.max() > 0xFFFF:
        raise SystemExit(f"table does not fit in uint16: {t.min()}..{t.max()}")

    parts = [HEADER.format(md5=md5, n=t.size, mx=int(t.max()))]
    row: list[str] = []
    for i, v in enumerate(t.tolist()):
        row.append(f"{int(v)},")
        if len(row) == 16:
            parts.append("\t" + " ".join(row) + "\n")
            row = []
    if row:
        parts.append("\t" + " ".join(row) + "\n")
    parts.append("}\n")
    return "".join(parts), md5


def main(argv: list[str]) -> int:
    src, md5 = build()
    if "--check" in argv:
        if not OUT.exists():
            print(f"MISSING: {OUT}")
            return 1
        if OUT.read_text() != src:
            print(f"STALE: {OUT} does not match {NPY} (md5 {md5}); "
                  f"re-run without --check")
            return 1
        print(f"OK: {OUT.relative_to(ROOT)} is current (npy md5 {md5})")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(src)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(src):,} bytes, npy md5 {md5})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
